# Generated by Django 4.2.16 on 2024-10-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_userdetail_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='writer',
            field=models.CharField(default='', max_length=100),
        ),
    ]
