# Generated by Django 4.2.16 on 2024-10-08 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_bookinfo_uploaded_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('address_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.userdetail')),
            ],
        ),
    ]
