# Generated by Django 4.2.16 on 2024-10-08 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_shippingaddresses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddresses',
            name='address_of',
        ),
        migrations.AddField(
            model_name='shippingaddresses',
            name='details_of',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.userdetail'),
        ),
        migrations.AddField(
            model_name='shippingaddresses',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
