# Generated by Django 4.2.16 on 2024-10-08 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_shippingaddresses_address_of_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='user_type',
        ),
    ]
