# Generated by Django 4.2.16 on 2024-10-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_userdetail_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddresses',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='shippingaddresses',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
